### ISSUE TITLE
Provide a License

### ISSUE THREAD

**Issue by BenjaminGlusa** [ryanmcdermott/typescript-makefile#3]
This seems like overkill but afaik providing no license (or an empty license) means, that no one may use the project in any way; not even in private / personal contexts.

I would recommend CC-0 1.0 which would render the repo as `public domain` but also protects you from warranties.

**Comment by ryanmcdermott** [comment]
Done in: ad6f5c262a77c06b938889c575e9c3ae778bc2bd

Thank you!

**Comment by BenjaminGlusa** [comment]
Awesome. Thank you.
